export default {
    deal_status_id: null,
    deal_category_id: null,
    deal_sub_category_id: null,
    submit_by_user_id: null,
    summary: null,
    investment_amount_sought: null,
    minimum_investment: null,
    expected_close_date: null,
    actual_close_date: null,
    short_description: null,
    company_name: null,
    sponsor_name: null,
    location: null,
    deal_instrument_id: null,
    projected_irr: null,
    projected_multiple: null,
    referred_by: null,
    valuation: null,
    stage: null,
    deal_contact_name: null,
    deal_contact_email: null,
    deal_industry_id: null,
    deal_profile: null
}